#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase

rm -rf 0
cp -rf 0.org 0
rm -rf 0.[0-9] [1-9]*

#------------------------------------------------------------------------------
